language: go

services:
  - docker

stages:
  - test
  - push

jobs:
  include:
    - stage: test
      script: go test
    - stage: push
      script: 
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH .
        - docker push $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH
